name: Validate Renovate Configuration
on: [ push, pull_request ]

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Install Renovate
        run: npm install -g renovate

      - name: Validate Renovate config
        run: npx --yes --package renovate -- renovate-config-validator --strict
