name: Validate Renovate Configuration
on: [ push, pull_request ]

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Install Renovate
        run: npm install -g renovate

      - name: Validate Renovate config
        run: npx --yes --package renovate -- renovate-config-validator --strict
